POST http://localhost:8080/patient/responses

<> 2022-03-26T171420.200.html

###

POST http://localhost:8080/api/v1/registration

<> 2022-03-22T005722.400.json

###

GET http://localhost:8080/api/v1/registration/conform

<> 2022-03-22T005645.400.json

###

