spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
#  mail:
#    host: localhost
#    port: 1025
#    username: hello
#    password: hello
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
  mail:
    host: smtp.gmail.com
    username: kaushiksai2395@gmail.com
    password: Pigwidgeon@2395
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  PatientLogin.app.jwtSecret : patientSecretKey
  PatientLogin.app.jwtExpirationMs : 86400000